# Use the production image as base image
FROM rcsalles/node-sorting-service

# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev


WORKDIR /usr/src/app

RUN npm install

EXPOSE 8080

CMD ["npm", "test"]